
import javafx.scene.control.Spinner;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Paulo.Bezerra
 */
public class Exercicio6 extends javax.swing.JFrame {

    public double CalcularPoupado(int porcentagem, int meses) {

        double total = 0;
        double renda = 0;
        boolean rendavalida = false;

        do {
            try {

                renda = (Double.valueOf(JSalario.getText()));
                rendavalida = !rendavalida;

            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(null, "Renda inválida");
                break;
            }
        } while (!rendavalida);

        total = (porcentagem * renda / 100) * meses;

        return total;
    }

    /**
     *
     *
     *
     * Creates new form Exercicio6
     */
    public Exercicio6() {
        initComponents();
        JSalario.setText("");
        JTotal.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpinnerRenda = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        JSalario = new javax.swing.JTextField();
        JCalcular = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSpinnerMeses = new javax.swing.JSpinner();
        JTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("% Renda Mensal");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 40, 120, 20);
        getContentPane().add(jSpinnerRenda);
        jSpinnerRenda.setBounds(162, 83, 70, 30);

        jLabel2.setText("Salário");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(23, 43, 80, 14);

        JSalario.setText("jTextField1");
        JSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSalarioActionPerformed(evt);
            }
        });
        getContentPane().add(JSalario);
        JSalario.setBounds(23, 83, 90, 30);

        JCalcular.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JCalcular.setText("Calcular");
        JCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(JCalcular);
        JCalcular.setBounds(23, 172, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Valor Total");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 176, 110, 20);

        jLabel4.setText("Meses Economizados");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(273, 43, 110, 14);
        getContentPane().add(jSpinnerMeses);
        jSpinnerMeses.setBounds(300, 83, 60, 30);

        JTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        JTotal.setText("jLabel5");
        getContentPane().add(JTotal);
        JTotal.setBounds(20, 213, 350, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSalarioActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_JSalarioActionPerformed

    private void JCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCalcularActionPerformed

        JSalarioActionPerformed(evt);        // TODO add your handling code here:
        int rendamensal = (Integer) jSpinnerRenda.getValue();
        int meseseconomizados = (Integer) jSpinnerMeses.getValue();
        double total = CalcularPoupado(rendamensal, meseseconomizados);
        String formatar = String.format("A renda será de R$ %.2f", total);
        JTotal.setText(String.valueOf(formatar));
    }//GEN-LAST:event_JCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Exercicio6 telaInicial = new Exercicio6();
                telaInicial.setSize(450, 400);
                telaInicial.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JCalcular;
    private javax.swing.JTextField JSalario;
    private javax.swing.JLabel JTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSpinnerMeses;
    private javax.swing.JSpinner jSpinnerRenda;
    // End of variables declaration//GEN-END:variables
}
