
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Paulo.Bezerra
 */
public class Exercicio5 extends javax.swing.JFrame {

    int vitorias = 0;
    int derrotas = 0;

    public void Jogada(String Jogada) {

        String computador = "";
        int numero;

        Random maquina = new Random();
        numero = maquina.nextInt(3) + 1;

        if (numero == 1) {
            computador = "Pedra";
        } else if (numero == 2) {
            computador = "Papel";
        } else if (numero == 3) {
            computador = "Tesoura";
        }

        if (Jogada.equals(computador)) {
            JOptionPane.showMessageDialog(null, "Empatou! Você jogou " + Jogada + " e a máquina jogou " + computador);
        } else if (Jogada.equals("Tesoura") && computador.equals("Pedra")) {
            JOptionPane.showMessageDialog(null, "Perdeu HUEHUE! Você jogou " + Jogada + " e a máquina jogou " + computador);
            derrotas++;
            JDerrota.setText(String.valueOf(derrotas));
        } else if (Jogada.equals("Pedra") && computador.equals("Papel")) {
            JOptionPane.showMessageDialog(null, "Perdeu HUEHUE! Você jogou " + Jogada + " e a máquina jogou " + computador);
            derrotas++;
            JDerrota.setText(String.valueOf(derrotas));
        } else if (Jogada.equals("Papel") && computador.equals("Tesoura")) {
            JOptionPane.showMessageDialog(null, "Perdeu HUEHUE! Você jogou " + Jogada + " e a máquina jogou " + computador);
            derrotas++;
            JDerrota.setText(String.valueOf(derrotas));
        } else {
            JOptionPane.showMessageDialog(null, "Ganhou MISERAVI! Você jogou " + Jogada + " e a máquina jogou " + computador);
            vitorias++;
            JVitoria.setText(String.valueOf(vitorias));

        }

    }

    /**
     * Creates new form Exercicio5
     */
    public Exercicio5() {
        initComponents();

        JVitoria.setText("0");
        JDerrota.setText("0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPedra = new javax.swing.JButton();
        JPapel = new javax.swing.JButton();
        JTesoura = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        JVitoria = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JDerrota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        JPedra.setText("Pedra");
        JPedra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPedraActionPerformed(evt);
            }
        });
        getContentPane().add(JPedra);
        JPedra.setBounds(40, 110, 90, 30);

        JPapel.setText("Papel");
        JPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JPapelActionPerformed(evt);
            }
        });
        getContentPane().add(JPapel);
        JPapel.setBounds(140, 110, 90, 30);

        JTesoura.setText("Tesoura");
        JTesoura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTesouraActionPerformed(evt);
            }
        });
        getContentPane().add(JTesoura);
        JTesoura.setBounds(240, 110, 100, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Vitórias");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 210, 80, 20);

        JVitoria.setText("jLabel2");
        getContentPane().add(JVitoria);
        JVitoria.setBounds(40, 240, 34, 14);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Derrotas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 210, 70, 20);

        JDerrota.setText("jLabel4");
        getContentPane().add(JDerrota);
        JDerrota.setBounds(250, 240, 34, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JPedraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPedraActionPerformed

        String jogada = "Pedra";
        Jogada(jogada);

        // TODO add your handling code here:
    }//GEN-LAST:event_JPedraActionPerformed

    private void JPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JPapelActionPerformed

        String jogada = "Papel";
        Jogada(jogada);// TODO add your handling code here:
    }//GEN-LAST:event_JPapelActionPerformed

    private void JTesouraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTesouraActionPerformed

        String jogada = "Tesoura";
        Jogada(jogada);        // TODO add your handling code here:
    }//GEN-LAST:event_JTesouraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Exercicio5 telaInicial = new Exercicio5();
                telaInicial.setSize(450, 400);
                telaInicial.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JDerrota;
    private javax.swing.JButton JPapel;
    private javax.swing.JButton JPedra;
    private javax.swing.JButton JTesoura;
    private javax.swing.JLabel JVitoria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
