
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Paulo.Bezerra
 */
public class Exercicio7 extends javax.swing.JFrame {

    public void TipoTriangulo() {

        double ladoA = 0;
        double ladoB = 0;
        double ladoC = 0;
        boolean ladosvalidos = false;

        do {
            try {

                ladoA = (Double.valueOf(jTextField1.getText()));
                ladoB = (Double.valueOf(jTextField2.getText()));
                ladoC = (Double.valueOf(jTextField3.getText()));
                ladosvalidos = !ladosvalidos;
            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(null, "Lados inválidos");
                break;
            }
        } while (!ladosvalidos);

        if (ladoA == ladoB && ladoB == ladoC && ladoA > 0) {
            System.out.println("As medidas " + ladoA + ", " + ladoB + " e " + ladoC + " formam um triangulo Equilátero");
            JMensagem.setText("As medidas " + String.valueOf(ladoA) + ", " + String.valueOf(ladoB) + " e " + String.valueOf(ladoC) + " formam um triangulo Equilátero");
        } else if (ladoA == ladoB && ladoA > 0 || ladoA == ladoC && ladoA > 0) {
            System.out.println("As medidas " + ladoA + ", " + ladoB + " e " + ladoC + " formam um triangulo Isósceles");
            JMensagem.setText("As medidas " + String.valueOf(ladoA) + ", " + String.valueOf(ladoB) + " e " + String.valueOf(ladoC) + " formam um triangulo Isósceles");
        } else if (ladoA != ladoB || ladoA != ladoC) {
            System.out.println("As medidas " + ladoA + ", " + ladoB + " e " + ladoC + " formam um triangulo Escaleno");
            JMensagem.setText("As medidas " + String.valueOf(ladoA) + ", " + String.valueOf(ladoB) + " e " + String.valueOf(ladoC) + " formam um triangulo Escaleno");

        } else {
            System.out.println("As medidas " + ladoA + ", " + ladoB + " e " + ladoC + " não formam um triângulo");
            JMensagem.setText("As medidas " + String.valueOf(ladoA) + ", " + String.valueOf(ladoB) + " e " + String.valueOf(ladoC) +" não formam um triângulo");
        }

    }

    /**
     * Creates new form Exercicio7
     */
    public Exercicio7() {
        initComponents();
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        JMensagem.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        JMensagem = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(48, 95, 90, 30);

        jTextField2.setText("jTextField2");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField2);
        jTextField2.setBounds(157, 95, 80, 30);

        jTextField3.setText("jTextField3");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(262, 95, 80, 30);

        jLabel1.setText("Lado A");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(57, 63, 60, 30);

        jLabel2.setText("Lado B");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(167, 63, 50, 30);

        jLabel3.setText("Lado C");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(272, 63, 60, 30);

        jButton1.setText("Calcular");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(140, 160, 100, 40);

        JMensagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JMensagem.setText("jLabel4");
        getContentPane().add(JMensagem);
        JMensagem.setBounds(10, 220, 370, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jTextField1ActionPerformed(evt);
        jTextField2ActionPerformed(evt);
        jTextField2ActionPerformed(evt);

        TipoTriangulo();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Exercicio7 telaInicial = new Exercicio7();
                telaInicial.setSize(450, 400);
                telaInicial.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JMensagem;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
