
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Paulo.Bezerra
 */
public class Exercicio4 extends javax.swing.JFrame {

    int contador = 0;
    int maiornumero = 0;
    int menornumero = 999999;
    double media = 0;

    public void MaiorNumero() {
        int[] idade = new int[9];
        boolean idadevalida = false;

        do {
            try {

                idade[contador] = (Integer.valueOf(jTextField1.getText()));
                idadevalida = !idadevalida;
                if (idade[contador] > maiornumero) {
                    maiornumero = idade[contador];
                }
                if (idade[contador] < menornumero) {
                  menornumero = idade[contador];

                }

                media += idade[contador];

                contador++;
                jLabel3.setText(String.valueOf(contador + 1));
                //JOptionPane.showMessageDialog(null, "Idade inválida");
                jTextField1.setText("");

            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(null, "Idade inválida");
                break;
            }
        } while (!idadevalida && contador < 9);
        idadevalida = !idadevalida;


    }

    /**
     * Creates new form Exercicio4
     */
    public Exercicio4() {
        initComponents();

        LabelMenor.setText("");
        LabelMaior.setText("");

        LabelMedia.setText("");
        jLabel3.setText(String.valueOf(contador + 1));
        jTextField1.setText("");

        int contador = 0;
        boolean idadevalida = false;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        LabelMedia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LabelMaior = new javax.swing.JLabel();
        LabelMenor = new javax.swing.JLabel();
        jmediatitulo = new javax.swing.JLabel();
        jmaiortitulo = new javax.swing.JLabel();
        jmenortitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 96, 262, 73);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(278, 96, 112, 73);

        LabelMedia.setText("jLabel1");
        getContentPane().add(LabelMedia);
        LabelMedia.setBounds(270, 210, 60, 62);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Insira a idade da pessoa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 50, 180, 30);

        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 60, 60, 20);

        LabelMaior.setText("jLabel1");
        getContentPane().add(LabelMaior);
        LabelMaior.setBounds(20, 210, 60, 62);

        LabelMenor.setText("jLabel1");
        getContentPane().add(LabelMenor);
        LabelMenor.setBounds(150, 210, 60, 62);

        jmediatitulo.setText("Media");
        getContentPane().add(jmediatitulo);
        jmediatitulo.setBounds(260, 180, 80, 16);

        jmaiortitulo.setText("Maior");
        getContentPane().add(jmaiortitulo);
        jmaiortitulo.setBounds(20, 180, 80, 16);

        jmenortitulo.setText("Menor");
        getContentPane().add(jmenortitulo);
        jmenortitulo.setBounds(140, 180, 80, 16);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        jTextField1ActionPerformed(evt);

        MaiorNumero();
        if (contador == 9) {

            LabelMaior.setText(String.valueOf(maiornumero));
            LabelMenor.setText(String.valueOf(menornumero));
            LabelMedia.setText(String.valueOf(media / 10));

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Exercicio4 telaInicial = new Exercicio4();
                telaInicial.setSize(450, 400);
                telaInicial.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelMaior;
    private javax.swing.JLabel LabelMedia;
    private javax.swing.JLabel LabelMenor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel jmaiortitulo;
    private javax.swing.JLabel jmediatitulo;
    private javax.swing.JLabel jmenortitulo;
    // End of variables declaration//GEN-END:variables
}
