
import java.awt.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Paulo.Bezerra
 */
public class Exercicio3 extends javax.swing.JFrame {

    public void printarcompra(String produto) {

        JOptionPane.showMessageDialog(null, "O produto " + produto + " foi adicionado");
    }

    String produto;

    String[] carrinhoproduto = new String[5];
    int[] carrinhoquantidade = new int[5];
    double[] precoproduto = new double[5];
    double precofinal;
    int contadorproduto = 0;
    int contadorquantidade = 0;
    boolean quantidadeinvalida = false;

    /**
     * Creates new form Exercicio3
     */
    public Exercicio3() {
        initComponents();
        jSpinner1.setValue(1);
        jLabel4.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JButtonAdicionar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JButtonFinalizarCompra = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Produto","Pão", "Leite", "Mortadela", "Presunto", "Queijo", "Salame", "Salgado", "Refrigerante", "Sorvete Palito", "Sorvete Casquinha", "Chocolate em Barra" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(65, 117, 348, 57);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Selecione o Produto");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 80, 348, 36);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Quantidade");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 80, 113, 43);

        JButtonAdicionar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JButtonAdicionar.setText("Adicionar ao Carrinho");
        JButtonAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonAdicionar);
        JButtonAdicionar.setBounds(75, 211, 160, 36);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Valor Final da Compra");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(75, 286, 177, 28);

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(75, 332, 187, 40);

        JButtonFinalizarCompra.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        JButtonFinalizarCompra.setText("Finalizar Compra");
        JButtonFinalizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonFinalizarCompraActionPerformed(evt);
            }
        });
        getContentPane().add(JButtonFinalizarCompra);
        JButtonFinalizarCompra.setBounds(294, 211, 139, 36);
        getContentPane().add(jSpinner1);
        jSpinner1.setBounds(480, 120, 70, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAdicionarActionPerformed

        produto = jComboBox1.getSelectedItem().toString();

        do {
            try {

                carrinhoquantidade[contadorquantidade] = (Integer) jSpinner1.getValue();
                System.out.println("QUANTIDADE " + carrinhoquantidade[contadorquantidade]);
                quantidadeinvalida = !quantidadeinvalida;
            } catch (NumberFormatException erro) {
                JOptionPane.showMessageDialog(null, "Insira a quantidade");
                break;
            }
        } while (!quantidadeinvalida);

        if (contadorproduto == 4) {
            JOptionPane.showMessageDialog(null, "Você já possui 5 produtos. Finalize a Compra");

        }

        if (produto.equals("Pão") && (carrinhoquantidade[contadorquantidade] >= 1)) {
            precoproduto[contadorproduto] = 0.7;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Leite") && carrinhoquantidade[contadorquantidade] >= 1) {
            precoproduto[contadorproduto] = 2.5;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Mortadela") && carrinhoquantidade[contadorquantidade] > 1) {
            precoproduto[contadorproduto] = 1.5;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Presunto") && carrinhoquantidade[contadorquantidade] > 1) {
            precoproduto[contadorproduto] = 1.5;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Queijo") && carrinhoquantidade[contadorquantidade] > 1) {
            precoproduto[contadorproduto] = 1.5;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Salame") && carrinhoquantidade[contadorquantidade] > 1) {
            precoproduto[contadorproduto] = 3.0;
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Salgado") && carrinhoquantidade[contadorquantidade] > 1) {
            precoproduto[contadorproduto] = 5.0;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Refrigerante") && carrinhoquantidade[contadorquantidade] > 1) {
            precoproduto[contadorproduto] = 4.0;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Sorvete Palito") && carrinhoquantidade[contadorquantidade] > 1) {
            precoproduto[contadorproduto] = 2.0;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Sorvete Casquinha") && carrinhoquantidade[contadorquantidade] > 1) {
            precoproduto[contadorproduto] = 4.0;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else if (produto.equals("Chocolate em Barra") && carrinhoquantidade[contadorquantidade] > 1) {
            precoproduto[contadorproduto] = 4.99;
            printarcompra(produto);
            contadorproduto++;
            contadorquantidade++;
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o Produto/Quantidade");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_JButtonAdicionarActionPerformed

    private void JButtonFinalizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonFinalizarCompraActionPerformed

        for (int i = 0; i < 5; i++) {

            precofinal = precofinal + precoproduto[i] * carrinhoquantidade[i];
            System.out.println(precoproduto[i]);

        }

        String formatar = String.format("R$ %.2f", precofinal);

        jLabel4.setText(formatar);

        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonFinalizarCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                Exercicio3 telaInicial = new Exercicio3();
                telaInicial.setSize(600, 450);
                telaInicial.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAdicionar;
    private javax.swing.JButton JButtonFinalizarCompra;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
