
import java.util.Random;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Paulo.Bezerra
 */
public class Exercicio8 extends javax.swing.JFrame {

    int contador = 0;
    String popup = "";
    String[] filmes = new String[50];
    int[] nota = new int[50];
    int sorteio = 0;
    int sorteado = 0;

    public class Filmes {

        public void Adicionar() {

            boolean notavalida = false;

            do {
                try {
                    filmes[contador] = String.valueOf(JNome.getText());
                    nota[contador] = (Integer.valueOf(JNota.getText()));
                    notavalida = !notavalida;
                    contador++;

                } catch (NumberFormatException erro) {
                    JOptionPane.showMessageDialog(null, "Nota inválida");
                    break;
                }
            } while (!notavalida);
            JNome.setText("");
            JNota.setText("");

        }

        public void PrintarFilmes() {

            for (int i = 0; i < filmes.length; i++) {
                if (filmes[i] != null) {
                    popup += filmes[i] + " Nota: "+nota[i]+"\n";
                }
            }
            JOptionPane.showMessageDialog(null, popup);

        }

        public void ExcluirLita() {

            for (int i = 0; i < filmes.length; i++) {
                filmes[i] = null;
                contador = 0;
            }
            JOptionPane.showMessageDialog(null, "Lista excluída");

        }

        public void SortearFilme() {
            Random random = new Random();
            for (int i = 0; i < filmes.length; i++) {
                if (filmes[i] != null) {
                    sorteio++;
                }

            }
            sorteado = random.nextInt((sorteio-1));
            JOptionPane.showMessageDialog(null, "O Filme indicado foi " + filmes[sorteado]);

        }

    }

    /**
     * Creates new form Exercicio8
     */
    public Exercicio8() {
        initComponents();
        JNome.setText("");
        JNota.setText("");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JNome = new javax.swing.JTextField();
        JNota = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JCadastrar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        JNome.setText("jTextField1");
        JNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNomeActionPerformed(evt);
            }
        });
        getContentPane().add(JNome);
        JNome.setBounds(43, 66, 171, 39);

        JNota.setText("jTextField2");
        JNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JNotaActionPerformed(evt);
            }
        });
        getContentPane().add(JNota);
        JNota.setBounds(300, 70, 59, 39);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Insira o nome do Filme");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(22, 41, 204, 19);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Insira a nota do Filme");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(258, 43, 167, 17);

        JCadastrar.setText("Cadastrar");
        JCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(JCadastrar);
        JCadastrar.setBounds(43, 116, 132, 23);

        jButton2.setText("Mostrar Lista");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(43, 157, 132, 23);

        jButton3.setText("Excluir Lista");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(40, 240, 132, 23);

        jButton1.setText("Indicar Filme");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 200, 130, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNomeActionPerformed

    private void JNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JNotaActionPerformed

    private void JCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCadastrarActionPerformed
        JNotaActionPerformed(evt);
        JNomeActionPerformed(evt);

        Filmes filme = new Filmes();

        filme.Adicionar();

// TODO add your handling code here:
    }//GEN-LAST:event_JCadastrarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Filmes printar = new Filmes();

        printar.PrintarFilmes();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        Filmes excluir = new Filmes();

        excluir.ExcluirLita();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Filmes sorteio = new Filmes();

        sorteio.SortearFilme();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {


        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio8.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio8.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio8.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio8.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Exercicio8 telaInicial = new Exercicio8();
                telaInicial.setSize(450, 400);
                telaInicial.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JCadastrar;
    private javax.swing.JTextField JNome;
    private javax.swing.JTextField JNota;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
