/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.RelatoriosBanco;

/**
 *
 * @author paulo.bezerra
 */
public class RelatoriosTela extends javax.swing.JFrame {

    /**
     * Creates new form Relatorios
     */
    public RelatoriosTela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        JResultadoReport = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboRelatorios = new javax.swing.JComboBox<>();
        jComboReportIntervalo = new javax.swing.JComboBox<>();
        BotaoGerarRelatorio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Relatórios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 10, 190, 40);
        getContentPane().add(JResultadoReport);
        JResultadoReport.setBounds(110, 220, 340, 150);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Resultado");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 180, 90, 20);

        jComboRelatorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quantidade de Vendas", "Quantidade de Vendas Canceladas", "Novos Clientes", "Total de Clientes", "Maiores Compradors", "Total de Produtos", "Produtos mais Vendidos"}));
        getContentPane().add(jComboRelatorios);
        jComboRelatorios.setBounds(100, 90, 220, 40);

        jComboReportIntervalo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Essa semana", "Ultima semana", "Esse mês", "Selecionar periodo" }));
        getContentPane().add(jComboReportIntervalo);
        jComboReportIntervalo.setBounds(380, 90, 200, 40);

        BotaoGerarRelatorio.setText("Gerar");
        BotaoGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoGerarRelatorioActionPerformed(evt);
            }
        });
        getContentPane().add(BotaoGerarRelatorio);
        BotaoGerarRelatorio.setBounds(280, 150, 59, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoGerarRelatorioActionPerformed

        RelatoriosBanco relatoriosbbanco = new RelatoriosBanco();

        if (jComboRelatorios.getSelectedItem().equals("Total de Clientes")) {
            int quantidadeclientes = relatoriosbbanco.SelectQuantidadeClientes();
            JResultadoReport.setText(String.valueOf("A quantidade total de clientes é: " + quantidadeclientes));

        } else if (jComboRelatorios.getSelectedItem().equals("Total de Produtos")) {
            int quantidadeprodutos = relatoriosbbanco.SelectQuantidadeProdutos();
            JResultadoReport.setText(String.valueOf("A quantidade total de produtos é: " + quantidadeprodutos));

        }

        //int quantidadevendas = relatoriosbbanco.SelectQuantidadeVendas();

        //JResultadoReport.setText(String.valueOf("A quantidade de vendas foi: " + quantidadevendas));

        // TODO add your handling code here:
    }//GEN-LAST:event_BotaoGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatoriosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatoriosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatoriosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatoriosTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoGerarRelatorio;
    private javax.swing.JLabel JResultadoReport;
    private javax.swing.JComboBox<String> jComboRelatorios;
    private javax.swing.JComboBox<String> jComboReportIntervalo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
