package View;

import View.Usuarios.LoginTela;
import View.Usuarios.CadastroUsuariosTela;
import View.Produtos.CadastroProdutosTela;
import View.Produtos.AterarProdutoTela;
import View.Clientes.AlterarClienteTela;
import Controller.Clientes.ClienteCadastrado;
import Controller.TelaUnica;
import Model.Usuarios.LoginDados;
import Model.Usuarios.Usuarios;
import View.Clientes.CadastroClientesTela;
import View.Relatorios.RelatoriosTela;
import View.Vendas.VendasTela;
import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.JInternalFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author paulo.hbezerra
 */
public class MenuInicialTela extends javax.swing.JFrame {

    public String loginvendas;

    public boolean janelaaberta = false;

    /**
     * Creates new form Main
     */
    public MenuInicialTela(LoginDados logindados) {
        initComponents();
        Logado.setText("  User: " + logindados.getUserName());
        loginvendas = logindados.getUserName();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FundoInicial = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jsvendas = new javax.swing.JMenu();
        jsVendas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jsCadastrarCliente = new javax.swing.JMenuItem();
        jsAlterarCliente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jsCadastrarProdutos = new javax.swing.JMenuItem();
        jsAlterarProduto = new javax.swing.JMenuItem();
        jsUsuarios = new javax.swing.JMenu();
        jsUsuario = new javax.swing.JMenuItem();
        jsRelatorios = new javax.swing.JMenu();
        jsRelatorio = new javax.swing.JMenuItem();
        jsOption = new javax.swing.JMenu();
        jsSair = new javax.swing.JMenuItem();
        Logado = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FundoInicial.setDoubleBuffered(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/menu_inicial.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        FundoInicial.add(jLabel1);
        jLabel1.setBounds(0, 0, 1200, 700);

        jsvendas.setText("Vendas");

        jsVendas.setText("Vendas");
        jsVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsVendasActionPerformed(evt);
            }
        });
        jsvendas.add(jsVendas);

        jMenuBar1.add(jsvendas);

        jMenu2.setText("Clientes");

        jsCadastrarCliente.setText("Cadastrar cliente");
        jsCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsCadastrarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jsCadastrarCliente);

        jsAlterarCliente.setText("Alterar cliente");
        jsAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsAlterarClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jsAlterarCliente);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Produtos");

        jsCadastrarProdutos.setText("Cadastrar produto");
        jsCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsCadastrarProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(jsCadastrarProdutos);

        jsAlterarProduto.setText("Alterar produto");
        jsAlterarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsAlterarProdutoActionPerformed(evt);
            }
        });
        jMenu3.add(jsAlterarProduto);

        jMenuBar1.add(jMenu3);

        jsUsuarios.setText("Usuários");

        jsUsuario.setText("Cadastrar usuário");
        jsUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsUsuarioActionPerformed(evt);
            }
        });
        jsUsuarios.add(jsUsuario);

        jMenuBar1.add(jsUsuarios);

        jsRelatorios.setText("Relatórios");

        jsRelatorio.setText("Gerar relatório");
        jsRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsRelatorioActionPerformed(evt);
            }
        });
        jsRelatorios.add(jsRelatorio);

        jMenuBar1.add(jsRelatorios);

        jsOption.setText("Opções");

        jsSair.setText("Sair");
        jsSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jsSairActionPerformed(evt);
            }
        });
        jsOption.add(jsSair);

        jMenuBar1.add(jsOption);
        jMenuBar1.add(Logado);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FundoInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 699, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jsVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsVendasActionPerformed

        boolean venda = true;
        
        Controller.TelaUnica telaunica = new TelaUnica();
        
        telaunica.Telaunica(venda);
        
            VendasTela vendas = new VendasTela(loginvendas, FundoInicial);
            vendas.setSize(700, 600);
            this.FundoInicial.add(vendas);
            vendas.setVisible(true);
            vendas.setResizable(false);
            this.openFrameInCenter(vendas);
        

    }//GEN-LAST:event_jsVendasActionPerformed

    private void jsSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsSairActionPerformed

        dispose();

        LoginTela login = new LoginTela();

        login.setVisible(true);
        login.setSize(400, 250);
        login.setResizable(false);
        login.setLocationRelativeTo(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_jsSairActionPerformed

    private void jsUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsUsuarioActionPerformed
        CadastroUsuariosTela cadastroUsuarios = new CadastroUsuariosTela();

        this.FundoInicial.add(cadastroUsuarios);
        cadastroUsuarios.setVisible(true);
        cadastroUsuarios.setResizable(false);
        this.openFrameInCenter(cadastroUsuarios);
    }//GEN-LAST:event_jsUsuarioActionPerformed

    private void jsCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsCadastrarClienteActionPerformed

        CadastroClientesTela clientescadastro = new CadastroClientesTela();

        clientescadastro.setSize(700, 600);
        this.FundoInicial.add(clientescadastro);
        clientescadastro.setVisible(true);
        clientescadastro.setResizable(false);

        this.openFrameInCenter(clientescadastro);

    }//GEN-LAST:event_jsCadastrarClienteActionPerformed

    private void jsAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsAlterarClienteActionPerformed
        AlterarClienteTela alterarcliente = new AlterarClienteTela();
        alterarcliente.setSize(700, 600);
        this.FundoInicial.add(alterarcliente);
        alterarcliente.setVisible(true);
        alterarcliente.setResizable(false);
        this.openFrameInCenter(alterarcliente);
    }//GEN-LAST:event_jsAlterarClienteActionPerformed

    private void jsCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsCadastrarProdutosActionPerformed
        CadastroProdutosTela controleestoque = new CadastroProdutosTela();
        controleestoque.setSize(700, 600);
        this.FundoInicial.add(controleestoque);
        controleestoque.setVisible(true);
        controleestoque.setResizable(false);
        this.openFrameInCenter(controleestoque);
    }//GEN-LAST:event_jsCadastrarProdutosActionPerformed

    private void jsAlterarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsAlterarProdutoActionPerformed
        View.Produtos.AterarProdutoTela alterarproduto = new AterarProdutoTela();
        alterarproduto.setSize(700, 600);
        this.FundoInicial.add(alterarproduto);
        alterarproduto.setVisible(true);
        alterarproduto.setResizable(false);
        this.openFrameInCenter(alterarproduto);
    }//GEN-LAST:event_jsAlterarProdutoActionPerformed

    private void jsRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jsRelatorioActionPerformed
        RelatoriosTela relatorios = new RelatoriosTela();
        relatorios.setSize(700, 600);
        this.FundoInicial.add(relatorios);
        relatorios.setVisible(true);
        relatorios.setResizable(false);
        this.openFrameInCenter(relatorios);

    }//GEN-LAST:event_jsRelatorioActionPerformed

    public void openFrameInCenter(JInternalFrame InicialFundo) {
        Dimension desktopSize = FundoInicial.getSize();
        Dimension jInternalFrameSize = InicialFundo.getSize();
        int width = (desktopSize.width - jInternalFrameSize.width) / 2;
        int height = (desktopSize.height - jInternalFrameSize.height) / 2;
        InicialFundo.setLocation(width, height);
        InicialFundo.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicialTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicialTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicialTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicialTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //MenuInicialTela telaInicial = new MenuInicialTela();
                //telaInicial.setSize(800, 800);
                //telaInicial.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane FundoInicial;
    private javax.swing.JMenu Logado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jsAlterarCliente;
    private javax.swing.JMenuItem jsAlterarProduto;
    private javax.swing.JMenuItem jsCadastrarCliente;
    private javax.swing.JMenuItem jsCadastrarProdutos;
    private javax.swing.JMenu jsOption;
    private javax.swing.JMenuItem jsRelatorio;
    private javax.swing.JMenu jsRelatorios;
    private javax.swing.JMenuItem jsSair;
    private javax.swing.JMenuItem jsUsuario;
    private javax.swing.JMenu jsUsuarios;
    private javax.swing.JMenuItem jsVendas;
    private javax.swing.JMenu jsvendas;
    // End of variables declaration//GEN-END:variables

}
